# Generated by Django 3.2 on 2021-12-03 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Age_Group',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
                ('age', models.CharField(max_length=100)),
            ],
            bases=('base.basemodel',),
        ),
        migrations.CreateModel(
            name='Ammenities',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
                ('ammenities_name', models.CharField(blank=True, max_length=250, null=True)),
                ('ammenities_detail', models.TextField()),
            ],
            bases=('base.basemodel',),
        ),
        migrations.CreateModel(
            name='GymProfile',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
                ('gym_name', models.CharField(blank=True, max_length=250, null=True)),
                ('gym_theme', models.CharField(choices=[('red', 'red'), ('green', 'green'), ('brown', 'brown'), ('orange', 'orange'), ('pink', 'pink'), ('blue', 'blue'), ('lightgreen', 'lightgreen'), ('yellow', 'yellow'), ('purple', 'purple')], default='red', max_length=255)),
                ('fitness_type', models.CharField(choices=[('crossfit', 'crossfit'), ('yoga', 'yoga'), ('tai chi', 'tai chi'), ('dance', 'dance'), ('bootcamp', 'bootcamp'), ('pilates', 'pilates'), ('boxing', 'boxing'), ('barne', 'barne')], default='yoga', max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=250)),
                ('contact_number', models.CharField(max_length=12)),
                ('gym_image', models.FileField(blank=True, null=True, upload_to='Gymimage')),
                ('about', models.TextField()),
                ('gender_criteria', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unisex', 'Unisex')], max_length=50)),
                ('age_criteria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gymprofile.age_group')),
            ],
            bases=('base.basemodel',),
        ),
        migrations.CreateModel(
            name='GymTime',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
                ('time_text', models.CharField(default='', max_length=200)),
                ('open_at', models.TimeField()),
                ('close_at', models.TimeField()),
            ],
            bases=('base.basemodel',),
        ),
        migrations.CreateModel(
            name='HelpText',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
                ('help_text', models.TextField()),
            ],
            bases=('base.basemodel',),
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
                ('instructor_specializaton', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('gym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gymprofile.gymprofile')),
            ],
            bases=('base.basemodel',),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
                ('gym_location', models.CharField(blank=True, max_length=500, null=True)),
            ],
            bases=('base.basemodel',),
        ),
        migrations.CreateModel(
            name='Weekdays',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
                ('day', models.CharField(max_length=50)),
                ('int_day', models.CharField(default='', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Weekdays',
                'ordering': ['created_at'],
            },
            bases=('base.basemodel',),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
                ('transaction_reason', models.CharField(blank=True, max_length=200, null=True)),
                ('date_paid', models.DateField(blank=True, null=True)),
                ('transaction_amount', models.FloatField(blank=True, max_length=12, null=True)),
                ('frequency', models.CharField(choices=[('Monthly', 'Monthly'), ('Quaterly', 'Quaterly'), ('Yearly', 'Yearly'), ('One Time', 'One Time')], max_length=50, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], max_length=50, null=True)),
                ('gym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gymprofile.gymprofile')),
            ],
            bases=('base.basemodel',),
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
                ('package_name', models.CharField(max_length=250)),
                ('package_description', models.TextField(blank=True, default='', null=True)),
                ('package_price', models.FloatField()),
                ('class_passes', models.IntegerField()),
                ('package_duration', models.CharField(blank=True, max_length=10, null=True)),
                ('package_start_date', models.DateField(blank=True, null=True)),
                ('package_end_date', models.DateField(blank=True, null=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gymprofile.gymprofile')),
            ],
            options={
                'verbose_name_plural': 'Packages',
            },
            bases=('base.basemodel',),
        ),
        migrations.CreateModel(
            name='Online',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
                ('topic', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('img', models.FileField(null=True, upload_to='online')),
                ('date', models.DateField()),
                ('Type', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=10, null=True)),
                ('max_strength', models.CharField(max_length=50, null=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymprofile.gymprofile')),
                ('online_instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gymprofile.instructor')),
            ],
            bases=('base.basemodel',),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
                ('membership_title', models.CharField(max_length=250)),
                ('membership_description', models.TextField()),
                ('membership_duration', models.CharField(max_length=10)),
                ('membership_amount', models.CharField(max_length=100)),
                ('gym', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gymprofile.gymprofile')),
                ('membership_age_group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gymprofile.age_group')),
                ('select_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gymprofile.location')),
            ],
            bases=('base.basemodel',),
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
                ('occasion', models.CharField(max_length=255, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('gym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gymprofile.gymprofile')),
            ],
            bases=('base.basemodel',),
        ),
        migrations.AddField(
            model_name='gymprofile',
            name='city',
            field=models.ManyToManyField(blank=True, to='gymprofile.Location'),
        ),
        migrations.AddField(
            model_name='gymprofile',
            name='gym_timings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymprofile.gymtime'),
        ),
        migrations.AddField(
            model_name='gymprofile',
            name='opening_days',
            field=models.ManyToManyField(to='gymprofile.Weekdays'),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
                ('course_name', models.CharField(max_length=200)),
                ('seat_available', models.IntegerField()),
                ('course_image', models.FileField(blank=True, null=True, upload_to='course')),
                ('start_time', models.TimeField(default='10:00:00')),
                ('end_time', models.TimeField(default='11:00:00')),
                ('course_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unisex', 'Unisex')], default='', max_length=50)),
                ('course_start_date', models.DateField()),
                ('course_end_date', models.DateField()),
                ('no_of_participants', models.IntegerField()),
                ('no_of_classes', models.IntegerField(default=10)),
                ('course_price', models.FloatField(default='0')),
                ('level', models.CharField(choices=[('All', 'All'), ('Intermediate', 'Intermediate'), ('Advance', 'Advance')], default='Select Level', max_length=100)),
                ('is_expired', models.BooleanField(default=True)),
                ('course_age_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gymprofile.age_group')),
                ('course_scheduled_on', models.ManyToManyField(to='gymprofile.Weekdays')),
                ('gym', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gymprofile.gymprofile')),
                ('instructor_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gymprofile.instructor')),
                ('select_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gymprofile.location')),
            ],
            bases=('base.basemodel',),
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
                ('class_topic', models.CharField(max_length=200)),
                ('class_description', models.TextField(blank=True, null=True)),
                ('class_image', models.FileField(blank=True, null=True, upload_to='course')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('class_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unisex', 'Unisex')], default='', max_length=50)),
                ('class_price', models.IntegerField(default=5)),
                ('seat_available', models.IntegerField()),
                ('duration', models.CharField(default=0, max_length=200)),
                ('no_of_participants', models.IntegerField()),
                ('level', models.CharField(choices=[('All', 'All'), ('Intermediate', 'Intermediate'), ('Advance', 'Advance')], default='Select Level', max_length=100)),
                ('class_expiry_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('class_scheduled_on', models.ManyToManyField(to='gymprofile.Weekdays')),
                ('classes_age_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gymprofile.age_group')),
                ('gym', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gymprofile.gymprofile')),
                ('instructor_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gymprofile.instructor')),
                ('select_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gymprofile.location')),
            ],
            options={
                'verbose_name_plural': 'Classes',
            },
            bases=('base.basemodel',),
        ),
        migrations.CreateModel(
            name='ChooseAmmenties',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
                ('ammenties_detail', models.TextField()),
                ('ammenties_name', models.ManyToManyField(blank=True, to='gymprofile.Ammenities')),
                ('gym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gymprofile.gymprofile')),
            ],
            bases=('base.basemodel',),
        ),
        migrations.CreateModel(
            name='CancellationPolicy',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
                ('policy_title', models.TextField(default='')),
                ('policy_text', models.TextField(default='')),
                ('gym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gymprofile.gymprofile')),
            ],
            bases=('base.basemodel',),
        ),
        migrations.AddField(
            model_name='ammenities',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gymprofile.gymprofile'),
        ),
    ]
